"""
Comprehensive US Universities Academic Data
Generated curriculum data for major Computer Science and STEM programs
"""

from typing import Dict, Any

ACADEMIC_DATA: Dict[str, Dict[str, Any]] = {
    "University of Texas at Dallas": {
        "majors": {
            "Computer Science": {
                "courses": {
                    "UNIV1010": {"name": "Freshman Seminar", "credits": 1, "prereqs": [], "category": "gened"},
                    "CS1103": {"name": "Intro to Computer Science", "credits": 3, "prereqs": [], "category": "core"},
                    "CS1340": {"name": "Discrete Structures", "credits": 3, "prereqs": [], "category": "core"},
                    "MATH1325": {"name": "Applied Calculus", "credits": 3, "prereqs": [], "category": "math"},
                    "MATH2413": {"name": "Calculus II", "credits": 4, "prereqs": ["MATH1325"], "category": "math"},
                    "CS2305": {"name": "Discrete Structures II", "credits": 3, "prereqs": ["CS1340"], "category": "core"},
                    "CS2336": {"name": "Computer Science II", "credits": 3, "prereqs": ["CS1103"], "category": "core"},
                    "MATH2417": {"name": "Calculus III", "credits": 4, "prereqs": ["MATH2413"], "category": "math"},
                    "CS3305": {"name": "Algorithms and Data Structures", "credits": 3, "prereqs": ["CS2336", "CS1340"], "category": "core"},
                    "CS3336": {"name": "Computer Architecture", "credits": 3, "prereqs": ["CS2336"], "category": "core"},
                    "CS3345": {"name": "Data Structures", "credits": 3, "prereqs": ["CS3305"], "category": "core"},
                    "CS4315": {"name": "Operating Systems", "credits": 3, "prereqs": ["CS3345"], "category": "core"},
                    "CS4337": {"name": "Database Systems", "credits": 3, "prereqs": ["CS3305"], "category": "core"},
                    "CS4341": {"name": "Machine Learning", "credits": 3, "prereqs": ["CS3305", "STAT2332"], "category": "elective"},
                    "CS4329": {"name": "Software Engineering", "credits": 3, "prereqs": ["CS3345"], "category": "core"},
                    "CS4390": {"name": "Senior Design I", "credits": 3, "prereqs": ["CS4329"], "category": "capstone"},
                    "CS4391": {"name": "Senior Design II", "credits": 3, "prereqs": ["CS4390"], "category": "capstone"},
                    "STAT2332": {"name": "Statistics for Engineers", "credits": 3, "prereqs": ["MATH2413"], "category": "math"},
                    "ENGR1301": {"name": "Engineering Fundamentals", "credits": 3, "prereqs": [], "category": "gened"},
                    "HUMA1301": {"name": "Composition I", "credits": 3, "prereqs": [], "category": "humanities"},
                },
                "degree_requirements": {
                    "required_courses": ["UNIV1010", "CS1103", "CS1340", "MATH1325", "MATH2413", "CS2305", "CS2336", "MATH2417", "CS3305", "CS3336", "CS3345", "CS4315", "CS4337", "CS4329", "CS4390", "CS4391", "STAT2332"],
                    "min_credits": 120,
                    "min_humanities_credits": 9,
                    "min_elective_credits": 18,
                },
                "four_year_template": [
                    ["UNIV1010", "CS1103", "MATH1325", "ENGR1301"],
                    ["CS1340", "MATH2413", "HUMA1301", "GENED100"],
                    ["CS2336", "MATH2417", "CS2305", "HUMA1302"],
                    ["CS3305", "CS3336", "STAT2332", "GENED101"],
                    ["CS3345", "CS4337", "GENED102", "ELX100"],
                    ["CS4315", "CS4329", "ELX101", "ELX102"],
                    ["CS4341", "GENED103", "ELX103", "ELX104"],
                    ["CS4390", "CS4391", "ELX105", "ELX106"],
                ],
                "default_electives": ["CS4341"],
            },
            "Data Science": {
                "courses": {
                    "UNIV1010": {"name": "Freshman Seminar", "credits": 1, "prereqs": [], "category": "gened"},
                    "CS1103": {"name": "Intro to Computer Science", "credits": 3, "prereqs": [], "category": "core"},
                    "MATH1325": {"name": "Applied Calculus", "credits": 3, "prereqs": [], "category": "math"},
                    "STAT2332": {"name": "Statistics for Engineers", "credits": 3, "prereqs": [], "category": "math"},
                    "CS1340": {"name": "Discrete Structures", "credits": 3, "prereqs": [], "category": "core"},
                    "MATH2413": {"name": "Calculus II", "credits": 4, "prereqs": ["MATH1325"], "category": "math"},
                    "CS2336": {"name": "Computer Science II", "credits": 3, "prereqs": ["CS1103"], "category": "core"},
                    "STAT3355": {"name": "Statistical Methods", "credits": 3, "prereqs": ["STAT2332"], "category": "core"},
                    "CS3305": {"name": "Algorithms and Data Structures", "credits": 3, "prereqs": ["CS2336", "CS1340"], "category": "core"},
                    "STAT4354": {"name": "Regression Analysis", "credits": 3, "prereqs": ["STAT3355"], "category": "core"},
                    "CS3336": {"name": "Computer Architecture", "credits": 3, "prereqs": ["CS2336"], "category": "core"},
                    "CS4341": {"name": "Machine Learning", "credits": 3, "prereqs": ["CS3305", "STAT3355"], "category": "core"},
                    "CS4337": {"name": "Database Systems", "credits": 3, "prereqs": ["CS3305"], "category": "core"},
                    "STAT4361": {"name": "Statistical Computing", "credits": 3, "prereqs": ["CS3305", "STAT3355"], "category": "elective"},
                    "CS4329": {"name": "Software Engineering", "credits": 3, "prereqs": ["CS3305"], "category": "elective"},
                    "CS4390": {"name": "Capstone I", "credits": 3, "prereqs": ["CS4341", "CS4337"], "category": "capstone"},
                    "CS4391": {"name": "Capstone II", "credits": 3, "prereqs": ["CS4390"], "category": "capstone"},
                    "MATH2417": {"name": "Calculus III", "credits": 4, "prereqs": ["MATH2413"], "category": "math"},
                    "HUMA1301": {"name": "Composition I", "credits": 3, "prereqs": [], "category": "humanities"},
                },
                "degree_requirements": {
                    "required_courses": ["UNIV1010", "CS1103", "MATH1325", "STAT2332", "CS2336", "STAT3355", "CS3305", "STAT4354", "CS4341", "CS4337", "CS4390", "CS4391", "MATH2413"],
                    "min_credits": 120,
                    "min_humanities_credits": 9,
                    "min_elective_credits": 18,
                },
                "four_year_template": [
                    ["UNIV1010", "CS1103", "MATH1325", "HUMA1301"],
                    ["CS1340", "STAT2332", "MATH2413", "GENED100"],
                    ["CS2336", "MATH2417", "STAT3355", "HUMA1302"],
                    ["CS3305", "STAT4354", "GENED101", "GENED102"],
                    ["CS4341", "CS4337", "STAT4361", "ELX100"],
                    ["CS4329", "GENED103", "ELX101", "ELX102"],
                    ["GENED104", "ELX103", "ELX104", "ELX105"],
                    ["CS4390", "CS4391", "ELX106", "ELX107"],
                ],
                "default_electives": ["CS4341", "STAT4361"],
            },
        }
    },
    "University of Texas at Austin": {
        "majors": {
            "Computer Science": {
                "courses": {
                    "CS312H": {"name": "Data Structures", "credits": 3, "prereqs": [], "category": "core"},
                    "CS314H": {"name": "Honors Data Structures", "credits": 3, "prereqs": [], "category": "core"},
                    "CS311H": {"name": "Discrete Math", "credits": 3, "prereqs": [], "category": "core"},
                    "M316H": {"name": "Honors Applied Functions", "credits": 3, "prereqs": [], "category": "math"},
                    "M325K": {"name": "Discrete Math I", "credits": 3, "prereqs": [], "category": "math"},
                    "CS429H": {"name": "Honors Computer Architecture", "credits": 4, "prereqs": ["CS314H"], "category": "core"},
                    "CS439": {"name": "Algorithms", "credits": 3, "prereqs": ["CS314H", "M325K"], "category": "core"},
                    "CS354H": {"name": "Operating Systems", "credits": 3, "prereqs": ["CS429H"], "category": "core"},
                    "CS357": {"name": "Algorithms and Complexity", "credits": 3, "prereqs": ["CS439"], "category": "core"},
                    "CS371P": {"name": "Object-Oriented Programming", "credits": 3, "prereqs": ["CS312H"], "category": "core"},
                    "CS371D": {"name": "Software Engineering", "credits": 3, "prereqs": ["CS371P"], "category": "core"},
                    "CS378H": {"name": "Introduction to AI", "credits": 3, "prereqs": ["CS314H", "CS439"], "category": "elective"},
                    "CS381K": {"name": "Machine Learning", "credits": 3, "prereqs": ["CS439", "STAT305"], "category": "elective"},
                    "M343L": {"name": "Linear Algebra", "credits": 3, "prereqs": ["M316H"], "category": "math"},
                    "STAT301": {"name": "Intro to Statistics", "credits": 3, "prereqs": [], "category": "math"},
                    "STAT305": {"name": "Statistics for Sciences", "credits": 3, "prereqs": ["STAT301"], "category": "math"},
                    "UGS302": {"name": "Signature Experiential", "credits": 1, "prereqs": [], "category": "gened"},
                    "E302": {"name": "Rhetoric and Writing", "credits": 3, "prereqs": [], "category": "humanities"},
                },
                "degree_requirements": {
                    "required_courses": ["CS312H", "CS311H", "M316H", "CS429H", "CS439", "CS354H", "CS371P", "CS371D", "M343L", "STAT301"],
                    "min_credits": 120,
                    "min_humanities_credits": 18,
                    "min_elective_credits": 12,
                },
                "four_year_template": [
                    ["CS312H", "M316H", "UGS302", "E302"],
                    ["CS314H", "M325K", "GENED100", "GENED101"],
                    ["CS311H", "CS429H", "STAT301", "GENED102"],
                    ["CS439", "M343L", "CS371P", "GENED103"],
                    ["CS354H", "CS357", "STAT305", "ELX100"],
                    ["CS371D", "CS378H", "ELX101", "ELX102"],
                    ["CS381K", "GENED104", "ELX103", "ELX104"],
                    ["ELX105", "ELX106", "ELX107", "ELX108"],
                ],
                "default_electives": ["CS378H", "CS381K"],
            },
        }
    },
    "Massachusetts Institute of Technology": {
        "majors": {
            "Computer Science": {
                "courses": {
                    "6.0001": {"name": "Introduction to CS and Programming", "credits": 3, "prereqs": [], "category": "core"},
                    "18.053": {"name": "Single Variable Calculus", "credits": 3, "prereqs": [], "category": "math"},
                    "18.06": {"name": "Linear Algebra", "credits": 4, "prereqs": ["18.053"], "category": "math"},
                    "6.0002": {"name": "Introduction to Computational Thinking", "credits": 3, "prereqs": ["6.0001"], "category": "core"},
                    "6.1210": {"name": "Algorithms", "credits": 4, "prereqs": ["6.0002", "18.06"], "category": "core"},
                    "6.1220": {"name": "Data Structures and Algorithms", "credits": 4, "prereqs": ["6.1210"], "category": "core"},
                    "6.1800": {"name": "Discrete Mathematics", "credits": 4, "prereqs": ["18.053"], "category": "core"},
                    "6.1900": {"name": "Computer Systems Engineering", "credits": 4, "prereqs": ["6.1220"], "category": "core"},
                    "6.2000": {"name": "Computer Architecture", "credits": 4, "prereqs": ["6.1900"], "category": "core"},
                    "6.036": {"name": "Machine Learning", "credits": 4, "prereqs": ["6.1220", "18.06"], "category": "elective"},
                    "6.046": {"name": "Algorithm Design", "credits": 4, "prereqs": ["6.1210"], "category": "elective"},
                    "6.1620": {"name": "Formal Methods and Verification", "credits": 4, "prereqs": ["6.1800"], "category": "elective"},
                    "14.01": {"name": "Microeconomics", "credits": 3, "prereqs": [], "category": "social"},
                    "21M.051": {"name": "Humor", "credits": 3, "prereqs": [], "category": "humanities"},
                    "24.900": {"name": "Introduction to Linguistics", "credits": 3, "prereqs": [], "category": "humanities"},
                },
                "degree_requirements": {
                    "required_courses": ["6.0001", "6.0002", "18.053", "18.06", "6.1210", "6.1220", "6.1800", "6.1900", "6.2000"],
                    "min_credits": 128,
                    "min_humanities_credits": 24,
                    "min_elective_credits": 24,
                },
                "four_year_template": [
                    ["6.0001", "18.053", "24.900", "GENED100"],
                    ["6.0002", "18.06", "21M.051", "GENED101"],
                    ["6.1210", "6.1800", "GENED102", "GENED103"],
                    ["6.1220", "14.01", "ELX100", "ELX101"],
                    ["6.1900", "6.036", "ELX102", "ELX103"],
                    ["6.2000", "6.046", "ELX104", "ELX105"],
                    ["6.1620", "ELX106", "ELX107", "ELX108"],
                    ["THESIS300", "THESIS301", "ELX109", "ELX110"],
                ],
                "default_electives": ["6.036", "6.046", "6.1620"],
            },
        }
    },
    "Stanford University": {
        "majors": {
            "Computer Science": {
                "courses": {
                    "CS106A": {"name": "Programming Methodology", "credits": 3, "prereqs": [], "category": "core"},
                    "CS106B": {"name": "Programming Abstractions", "credits": 3, "prereqs": ["CS106A"], "category": "core"},
                    "CS109": {"name": "Data Science", "credits": 3, "prereqs": ["CS106B"], "category": "core"},
                    "CS110": {"name": "Principles of Computer Systems", "credits": 3, "prereqs": ["CS106B"], "category": "core"},
                    "CS161": {"name": "Design of Usable and Secure Interactive Systems", "credits": 3, "prereqs": ["CS106B"], "category": "core"},
                    "CS107": {"name": "Computer Systems from the Programmer's Perspective", "credits": 3, "prereqs": ["CS106B"], "category": "core"},
                    "CS111": {"name": "Operating Systems Principles", "credits": 3, "prereqs": ["CS107"], "category": "core"},
                    "CS103": {"name": "Mathematical Foundations of Computing", "credits": 3, "prereqs": [], "category": "core"},
                    "CS231N": {"name": "Convolutional Neural Networks", "credits": 3, "prereqs": ["CS109"], "category": "elective"},
                    "CS224N": {"name": "NLP with Deep Learning", "credits": 3, "prereqs": ["CS231N"], "category": "elective"},
                    "MATH51": {"name": "Linear Algebra, Multivariable Calculus", "credits": 5, "prereqs": [], "category": "math"},
                    "MATH52": {"name": "Integral Calculus of Several Variables", "credits": 5, "prereqs": ["MATH51"], "category": "math"},
                    "MATH53": {"name": "Ordinary Differential Equations", "credits": 3, "prereqs": ["MATH52"], "category": "math"},
                    "CA300": {"name": "Civilization", "credits": 3, "prereqs": [], "category": "humanities"},
                },
                "degree_requirements": {
                    "required_courses": ["CS106A", "CS106B", "CS109", "CS110", "CS107", "CS111", "MATH51", "MATH52", "MATH53", "CS103"],
                    "min_credits": 120,
                    "min_humanities_credits": 12,
                    "min_elective_credits": 24,
                },
                "four_year_template": [
                    ["CS106A", "MATH51", "CA300", "GENED100"],
                    ["CS106B", "MATH52", "GENED101", "GENED102"],
                    ["CS109", "CS110", "MATH53", "ELX100"],
                    ["CS107", "CS103", "ELX101", "ELX102"],
                    ["CS111", "CS161", "ELX103", "ELX104"],
                    ["CS231N", "GENED103", "ELX105", "ELX106"],
                    ["CS224N", "ELX107", "ELX108", "ELX109"],
                    ["ELX110", "ELX111", "ELX112", "ELX113"],
                ],
                "default_electives": ["CS231N", "CS224N"],
            },
        }
    },
    "Harvard University": {
        "majors": {
            "Computer Science": {
                "courses": {
                    "CS50": {"name": "Introduction to Computer Science", "credits": 4, "prereqs": [], "category": "core"},
                    "CS109": {"name": "Data Science", "credits": 4, "prereqs": ["CS50"], "category": "core"},
                    "CS110": {"name": "Advanced Algorithms and Data Structures", "credits": 4, "prereqs": ["CS50"], "category": "core"},
                    "CS179": {"name": "Design of Usable and Secure Interactive Systems", "credits": 3, "prereqs": ["CS50"], "category": "elective"},
                    "CS105": {"name": "Data Systems", "credits": 3, "prereqs": ["CS50"], "category": "core"},
                    "CS171": {"name": "Visualization", "credits": 3, "prereqs": ["CS50"], "category": "elective"},
                    "AM105": {"name": "Applied Mathematics", "credits": 3, "prereqs": [], "category": "math"},
                    "AM107": {"name": "Graph Theory and Complex Networks", "credits": 3, "prereqs": ["AM105"], "category": "math"},
                    "STAT110": {"name": "Probability", "credits": 4, "prereqs": [], "category": "math"},
                    "STAT101": {"name": "Data Science", "credits": 3, "prereqs": ["STAT110"], "category": "elective"},
                    "GEN1000": {"name": "General Education", "credits": 3, "prereqs": [], "category": "humanities"},
                    "HUMA1000": {"name": "Humanities", "credits": 3, "prereqs": [], "category": "humanities"},
                },
                "degree_requirements": {
                    "required_courses": ["CS50", "CS109", "CS110", "CS105", "STAT110", "AM105"],
                    "min_credits": 128,
                    "min_humanities_credits": 12,
                    "min_elective_credits": 18,
                },
                "four_year_template": [
                    ["CS50", "STAT110", "HUMA1000", "GEN1000"],
                    ["CS109", "AM105", "GEN1001", "GEN1002"],
                    ["CS110", "CS105", "AM107", "ELX100"],
                    ["CS179", "CS171", "STAT101", "ELX101"],
                    ["ELX102", "ELX103", "ELX104", "ELX105"],
                    ["ELX106", "ELX107", "ELX108", "ELX109"],
                    ["ELX110", "ELX111", "ELX112", "ELX113"],
                    ["ELX114", "ELX115", "ELX116", "ELX117"],
                ],
                "default_electives": ["CS179", "CS171", "STAT101"],
            },
        }
    },
    "University of California Berkeley": {
        "majors": {
            "Electrical Engineering and Computer Science": {
                "courses": {
                    "CS61A": {"name": "Structure and Interpretation of Computer Programs", "credits": 3, "prereqs": [], "category": "core"},
                    "CS61B": {"name": "Data Structures and Advanced Programming", "credits": 3, "prereqs": ["CS61A"], "category": "core"},
                    "CS61C": {"name": "Machine Structures", "credits": 3, "prereqs": ["CS61B"], "category": "core"},
                    "CS70": {"name": "Discrete Mathematics and Probability Theory", "credits": 3, "prereqs": [], "category": "core"},
                    "EE16A": {"name": "Designing Information Systems and Machines Part A", "credits": 3, "prereqs": [], "category": "core"},
                    "EE16B": {"name": "Designing Information Systems and Machines Part B", "credits": 3, "prereqs": ["EE16A"], "category": "core"},
                    "CS162": {"name": "Operating Systems and System Programming", "credits": 3, "prereqs": ["CS61C"], "category": "core"},
                    "CS170": {"name": "Efficient Algorithms and Intractable Problems", "credits": 3, "prereqs": ["CS70"], "category": "core"},
                    "CS188": {"name": "Introduction to Artificial Intelligence", "credits": 3, "prereqs": ["CS61B", "CS70"], "category": "elective"},
                    "CS189": {"name": "Machine Learning", "credits": 3, "prereqs": ["CS70", "EE16B"], "category": "elective"},
                    "MATH110": {"name": "Linear Algebra", "credits": 3, "prereqs": [], "category": "math"},
                    "MATH113": {"name": "Abstract Algebra", "credits": 3, "prereqs": ["MATH110"], "category": "math"},
                    "R1A": {"name": "Reading and Composition", "credits": 3, "prereqs": [], "category": "humanities"},
                },
                "degree_requirements": {
                    "required_courses": ["CS61A", "CS61B", "CS61C", "CS70", "EE16A", "EE16B", "CS162", "CS170", "MATH110"],
                    "min_credits": 128,
                    "min_humanities_credits": 15,
                    "min_elective_credits": 12,
                },
                "four_year_template": [
                    ["CS61A", "MATH110", "R1A", "GENED100"],
                    ["CS61B", "CS70", "EE16A", "GENED101"],
                    ["CS61C", "EE16B", "MATH113", "GENED102"],
                    ["CS162", "GENED103", "ELX100", "ELX101"],
                    ["CS170", "CS188", "ELX102", "ELX103"],
                    ["CS189", "GENED104", "ELX104", "ELX105"],
                    ["ELX106", "ELX107", "ELX108", "ELX109"],
                    ["ELX110", "ELX111", "ELX112", "ELX113"],
                ],
                "default_electives": ["CS188", "CS189"],
            },
        }
    },
    "Carnegie Mellon University": {
        "majors": {
            "Computer Science": {
                "courses": {
                    "15112": {"name": "Fundamentals of Programming and CS", "credits": 3, "prereqs": [], "category": "core"},
                    "15122": {"name": "Imperative Computation", "credits": 3, "prereqs": ["15112"], "category": "core"},
                    "15150": {"name": "Functional Programming", "credits": 3, "prereqs": ["15112"], "category": "core"},
                    "15151": {"name": "Mathematical Modeling for Computer Science", "credits": 3, "prereqs": [], "category": "math"},
                    "21127": {"name": "Concepts of Math", "credits": 3, "prereqs": [], "category": "math"},
                    "15251": {"name": "Great Ideas in Theoretical CS", "credits": 3, "prereqs": ["15122", "21127"], "category": "core"},
                    "15211": {"name": "Fundamental Data Structures", "credits": 3, "prereqs": ["15122"], "category": "core"},
                    "15213": {"name": "Introduction to Computer Systems", "credits": 3, "prereqs": ["15122"], "category": "core"},
                    "15330": {"name": "Algorithms and Advanced Data Structures", "credits": 3, "prereqs": ["15211", "15251"], "category": "core"},
                    "15445": {"name": "Database Systems", "credits": 3, "prereqs": ["15213"], "category": "elective"},
                    "15780": {"name": "Graduate AI", "credits": 3, "prereqs": ["15211", "21127"], "category": "elective"},
                    "15294": {"name": "CS in Society", "credits": 3, "prereqs": [], "category": "humanities"},
                    "76101": {"name": "History", "credits": 3, "prereqs": [], "category": "humanities"},
                },
                "degree_requirements": {
                    "required_courses": ["15112", "15122", "15150", "21127", "15251", "15211", "15213", "15330", "15151"],
                    "min_credits": 120,
                    "min_humanities_credits": 12,
                    "min_elective_credits": 18,
                },
                "four_year_template": [
                    ["15112", "21127", "15294", "76101"],
                    ["15122", "15150", "GENED100", "GENED101"],
                    ["15211", "15151", "GENED102", "GENED103"],
                    ["15213", "15251", "ELX100", "ELX101"],
                    ["15330", "15445", "ELX102", "ELX103"],
                    ["15780", "GENED104", "ELX104", "ELX105"],
                    ["ELX106", "ELX107", "ELX108", "ELX109"],
                    ["ELX110", "ELX111", "ELX112", "ELX113"],
                ],
                "default_electives": ["15445", "15780"],
            },
        }
    },
    "University of California Los Angeles": {
        "majors": {
            "Computer Science": {
                "courses": {
                    "CS31": {"name": "Introduction to Computer Science I", "credits": 4, "prereqs": [], "category": "core"},
                    "CS32": {"name": "Introduction to Computer Science II", "credits": 4, "prereqs": ["CS31"], "category": "core"},
                    "CS33": {"name": "Introduction to Computer Organization", "credits": 4, "prereqs": ["CS32"], "category": "core"},
                    "CS35L": {"name": "Software Construction Laboratory", "credits": 4, "prereqs": ["CS32"], "category": "core"},
                    "CS111": {"name": "Operating Systems Principles", "credits": 4, "prereqs": ["CS33"], "category": "core"},
                    "COM SCI 118": {"name": "Computer Networks", "credits": 4, "prereqs": ["CS111"], "category": "elective"},
                    "CS131": {"name": "Programming Languages", "credits": 4, "prereqs": ["CS32"], "category": "core"},
                    "CS180": {"name": "Algorithms and Complexity", "credits": 4, "prereqs": ["CS32", "MATH61"], "category": "core"},
                    "CS188": {"name": "Design of Usable Interactive Systems", "credits": 4, "prereqs": ["CS32"], "category": "elective"},
                    "CS161": {"name": "Artificial Intelligence", "credits": 4, "prereqs": ["CS31", "STATS100A"], "category": "elective"},
                    "MATH61": {"name": "Discrete Structures", "credits": 3, "prereqs": [], "category": "math"},
                    "MATH62": {"name": "Introduction to Linear Algebra and Applications", "credits": 5, "prereqs": [], "category": "math"},
                    "STATS100A": {"name": "Probability", "credits": 3, "prereqs": [], "category": "math"},
                },
                "degree_requirements": {
                    "required_courses": ["CS31", "CS32", "CS33", "CS35L", "CS111", "CS131", "CS180", "MATH61", "MATH62", "STATS100A"],
                    "min_credits": 120,
                    "min_humanities_credits": 12,
                    "min_elective_credits": 12,
                },
                "four_year_template": [
                    ["CS31", "MATH61", "GENED100", "GENED101"],
                    ["CS32", "MATH62", "GENED102", "GENED103"],
                    ["CS33", "STATS100A", "ELX100", "GENED104"],
                    ["CS35L", "CS131", "ELX101", "ELX102"],
                    ["CS111", "CS180", "ELX103", "ELX104"],
                    ["CS161", "CS188", "ELX105", "ELX106"],
                    ["COM SCI 118", "ELX107", "ELX108", "ELX109"],
                    ["ELX110", "ELX111", "ELX112", "ELX113"],
                ],
                "default_electives": ["CS161", "CS188", "COM SCI 118"],
            },
        }
    },
    "Georgia Institute of Technology": {
        "majors": {
            "Computer Science": {
                "courses": {
                    "CS1301": {"name": "Introduction to Computing", "credits": 3, "prereqs": [], "category": "core"},
                    "CS1331": {"name": "Introduction to Object Oriented Programming", "credits": 3, "prereqs": ["CS1301"], "category": "core"},
                    "CS1332": {"name": "Data Structures and Algorithms", "credits": 3, "prereqs": ["CS1331"], "category": "core"},
                    "CS2050": {"name": "Discrete Mathematics for CS", "credits": 3, "prereqs": [], "category": "core"},
                    "CS2110": {"name": "Computer Organization and Programming", "credits": 4, "prereqs": ["CS1332"], "category": "core"},
                    "CS2200": {"name": "Systems and Networks", "credits": 4, "prereqs": ["CS2110"], "category": "core"},
                    "CS3510": {"name": "Design and Analysis of Algorithms", "credits": 3, "prereqs": ["CS1332", "CS2050"], "category": "core"},
                    "CS3210": {"name": "Design of Operating Systems", "credits": 3, "prereqs": ["CS2200"], "category": "core"},
                    "CS4400": {"name": "Introduction to Database Systems", "credits": 3, "prereqs": ["CS2200"], "category": "elective"},
                    "CS4641": {"name": "Machine Learning", "credits": 3, "prereqs": ["CS2050", "CS1332"], "category": "elective"},
                    "MATH1501": {"name": "Calculus I", "credits": 4, "prereqs": [], "category": "math"},
                    "MATH1502": {"name": "Calculus II", "credits": 4, "prereqs": ["MATH1501"], "category": "math"},
                    "MATH2605": {"name": "Linear Algebra with Comp Applications", "credits": 3, "prereqs": ["MATH1502"], "category": "math"},
                },
                "degree_requirements": {
                    "required_courses": ["CS1301", "CS1331", "CS1332", "CS2050", "CS2110", "CS2200", "CS3510", "CS3210", "MATH1501", "MATH1502", "MATH2605"],
                    "min_credits": 120,
                    "min_humanities_credits": 12,
                    "min_elective_credits": 15,
                },
                "four_year_template": [
                    ["CS1301", "MATH1501", "GENED100", "GENED101"],
                    ["CS1331", "MATH1502", "GENED102", "GENED103"],
                    ["CS1332", "CS2050", "MATH2605", "GENED104"],
                    ["CS2110", "CS2200", "ELX100", "ELX101"],
                    ["CS3510", "CS3210", "ELX102", "ELX103"],
                    ["CS4400", "CS4641", "ELX104", "ELX105"],
                    ["ELX106", "ELX107", "ELX108", "ELX109"],
                    ["ELX110", "ELX111", "ELX112", "ELX113"],
                ],
                "default_electives": ["CS4400", "CS4641"],
            },
        }
    },
    "University of Michigan": {
        "majors": {
            "Computer Science": {
                "courses": {
                    "EECS183": {"name": "Elementary Programming Concepts", "credits": 4, "prereqs": [], "category": "core"},
                    "EECS280": {"name": "Programming and Data Structures", "credits": 4, "prereqs": ["EECS183"], "category": "core"},
                    "EECS203": {"name": "Discrete Mathematics", "credits": 4, "prereqs": [], "category": "core"},
                    "EECS376": {"name": "Foundations of Computer Science", "credits": 4, "prereqs": ["EECS280", "EECS203"], "category": "core"},
                    "EECS370": {"name": "Introduction to Computer Organization", "credits": 4, "prereqs": ["EECS280"], "category": "core"},
                    "EECS482": {"name": "Introduction to Operating Systems", "credits": 4, "prereqs": ["EECS370"], "category": "core"},
                    "EECS484": {"name": "Database Systems", "credits": 3, "prereqs": ["EECS280"], "category": "elective"},
                    "EECS492": {"name": "Introduction to Artificial Intelligence", "credits": 3, "prereqs": ["EECS280", "EECS203"], "category": "elective"},
                    "MATH116": {"name": "Calculus II", "credits": 4, "prereqs": [], "category": "math"},
                    "MATH214": {"name": "Applied Linear Algebra", "credits": 3, "prereqs": ["MATH116"], "category": "math"},
                    "STATS250": {"name": "Introduction to Statistics and Data Analysis", "credits": 3, "prereqs": ["MATH116"], "category": "math"},
                    "ENGR101": {"name": "Introduction to Engineering", "credits": 1, "prereqs": [], "category": "gened"},
                    "ENGLISH125": {"name": "Exposition and Argument", "credits": 3, "prereqs": [], "category": "humanities"},
                },
                "degree_requirements": {
                    "required_courses": ["EECS183", "EECS280", "EECS203", "EECS376", "EECS370", "EECS482", "MATH116", "MATH214", "STATS250"],
                    "min_credits": 120,
                    "min_humanities_credits": 12,
                    "min_elective_credits": 15,
                },
                "four_year_template": [
                    ["EECS183", "MATH116", "ENGR101", "ENGLISH125"],
                    ["EECS280", "EECS203", "GENED100", "GENED101"],
                    ["EECS370", "MATH214", "GENED102", "GENED103"],
                    ["EECS376", "STATS250", "ELX100", "ELX101"],
                    ["EECS482", "EECS484", "ELX102", "ELX103"],
                    ["EECS492", "GENED104", "ELX104", "ELX105"],
                    ["ELX106", "ELX107", "ELX108", "ELX109"],
                    ["ELX110", "ELX111", "ELX112", "ELX113"],
                ],
                "default_electives": ["EECS484", "EECS492"],
            },
        }
    },
    "State University": {
        "majors": {
            "Computer Science": {
                "courses": {
                    "FYS100": {"name": "First-Year Seminar", "credits": 1, "prereqs": [], "category": "gened"},
                    "ENG101": {"name": "College Writing", "credits": 3, "prereqs": [], "category": "gened"},
                    "MATH101": {"name": "Calculus I", "credits": 4, "prereqs": [], "category": "math"},
                    "MATH102": {"name": "Calculus II", "credits": 4, "prereqs": ["MATH101"], "category": "math"},
                    "CS101": {"name": "Intro to Programming", "credits": 4, "prereqs": [], "category": "core"},
                    "CS102": {"name": "Data Structures", "credits": 4, "prereqs": ["CS101"], "category": "core"},
                    "CS201": {"name": "Computer Organization", "credits": 3, "prereqs": ["CS102"], "category": "core"},
                    "CS210": {"name": "Discrete Mathematics", "credits": 3, "prereqs": ["MATH101"], "category": "core"},
                    "CS220": {"name": "Algorithms", "credits": 3, "prereqs": ["CS102", "CS210"], "category": "core"},
                    "CS230": {"name": "Databases", "credits": 3, "prereqs": ["CS102"], "category": "core"},
                    "CS240": {"name": "Operating Systems", "credits": 3, "prereqs": ["CS201"], "category": "core"},
                    "CS250": {"name": "Software Engineering", "credits": 3, "prereqs": ["CS220"], "category": "core"},
                    "STAT201": {"name": "Statistics", "credits": 3, "prereqs": ["MATH101"], "category": "math"},
                    "HUM101": {"name": "Humanities Elective", "credits": 3, "prereqs": [], "category": "humanities"},
                    "SOC101": {"name": "Social Science Elective", "credits": 3, "prereqs": [], "category": "social"},
                    "CS310": {"name": "Machine Learning", "credits": 3, "prereqs": ["CS220", "STAT201"], "category": "elective"},
                    "CS320": {"name": "Cybersecurity", "credits": 3, "prereqs": ["CS240"], "category": "elective"},
                    "CS330": {"name": "Mobile App Development", "credits": 3, "prereqs": ["CS250"], "category": "elective"},
                    "CS340": {"name": "Data Visualization", "credits": 3, "prereqs": ["CS230", "STAT201"], "category": "elective"},
                    "CS350": {"name": "Cloud Computing", "credits": 3, "prereqs": ["CS240"], "category": "elective"},
                    "CS360": {"name": "Natural Language Processing", "credits": 3, "prereqs": ["CS310"], "category": "elective"},
                    "CS490": {"name": "Senior Capstone", "credits": 3, "prereqs": ["CS250"], "category": "capstone"},
                },
                "degree_requirements": {
                    "required_courses": [
                        "FYS100", "ENG101", "MATH101", "MATH102", "CS101", "CS102", "CS201",
                        "CS210", "CS220", "CS230", "CS240", "CS250", "STAT201", "CS490",
                    ],
                    "min_credits": 120,
                    "min_humanities_credits": 6,
                    "min_social_credits": 6,
                    "min_elective_credits": 15,
                },
                "four_year_template": [
                    ["FYS100", "ENG101", "CS101", "MATH101"],
                    ["MATH102", "CS102", "HUM101", "SOC101"],
                    ["CS201", "CS210", "STAT201", "HUM101"],
                    ["CS220", "CS230", "SOC101", "ELX100"],
                    ["CS250", "ELX200", "ELX201", "GEN200"],
                    ["CS240", "ELX202", "ELX203", "GEN201"],
                    ["ELX300", "ELX301", "GEN300", "GEN301"],
                    ["CS490", "ELX302", "ELX303", "GEN302"],
                ],
                "default_electives": ["CS310", "CS320", "CS330", "CS340", "CS350"],
            },
            "Data Science": {
                "courses": {
                    "FYS100": {"name": "First-Year Seminar", "credits": 1, "prereqs": [], "category": "gened"},
                    "ENG101": {"name": "College Writing", "credits": 3, "prereqs": [], "category": "gened"},
                    "MATH101": {"name": "Calculus I", "credits": 4, "prereqs": [], "category": "math"},
                    "MATH102": {"name": "Calculus II", "credits": 4, "prereqs": ["MATH101"], "category": "math"},
                    "STAT201": {"name": "Statistics I", "credits": 3, "prereqs": ["MATH101"], "category": "math"},
                    "STAT310": {"name": "Applied Regression", "credits": 3, "prereqs": ["STAT201"], "category": "elective"},
                    "CS101": {"name": "Intro to Programming", "credits": 4, "prereqs": [], "category": "core"},
                    "CS102": {"name": "Data Structures", "credits": 4, "prereqs": ["CS101"], "category": "core"},
                    "DS200": {"name": "Data Wrangling", "credits": 3, "prereqs": ["CS101"], "category": "core"},
                    "DS210": {"name": "Data Ethics", "credits": 3, "prereqs": [], "category": "core"},
                    "DS220": {"name": "Data Visualization", "credits": 3, "prereqs": ["DS200", "STAT201"], "category": "core"},
                    "DS300": {"name": "Machine Learning Foundations", "credits": 3, "prereqs": ["CS102", "MATH102", "STAT201"], "category": "core"},
                    "DS330": {"name": "Applied Machine Learning", "credits": 3, "prereqs": ["DS300"], "category": "elective"},
                    "DS340": {"name": "Business Analytics", "credits": 3, "prereqs": ["DS220"], "category": "elective"},
                    "HUM101": {"name": "Humanities Elective", "credits": 3, "prereqs": [], "category": "humanities"},
                    "HUM102": {"name": "Humanities Elective II", "credits": 3, "prereqs": [], "category": "humanities"},
                    "SOC101": {"name": "Social Science Elective", "credits": 3, "prereqs": [], "category": "social"},
                    "SOC102": {"name": "Social Science Elective II", "credits": 3, "prereqs": [], "category": "social"},
                    "DS490": {"name": "Data Science Capstone", "credits": 3, "prereqs": ["DS300"], "category": "capstone"},
                },
                "degree_requirements": {
                    "required_courses": [
                        "FYS100", "ENG101", "MATH101", "MATH102", "STAT201", "CS101", "CS102",
                        "DS200", "DS210", "DS220", "DS300", "DS490",
                    ],
                    "min_credits": 120,
                    "min_humanities_credits": 6,
                    "min_social_credits": 6,
                    "min_elective_credits": 12,
                },
                "four_year_template": [
                    ["FYS100", "ENG101", "CS101", "MATH101"],
                    ["MATH102", "STAT201", "DS210", "HUM101"],
                    ["CS102", "DS200", "SOC101", "HUM102"],
                    ["DS220", "SOC102", "ELX100", "GEN200"],
                    ["DS300", "ELX200", "ELX201", "GEN201"],
                    ["ELX202", "ELX203", "GEN202", "GEN203"],
                    ["ELX300", "ELX301", "GEN300", "GEN301"],
                    ["DS490", "ELX302", "ELX303", "GEN302"],
                ],
                "default_electives": ["DS330", "DS340", "STAT310"],
            },
        }
    },
    "Metro Tech Institute": {
        "majors": {
            "Computer Science": {
                "courses": {
                    "COLL100": {"name": "College Success", "credits": 2, "prereqs": [], "category": "gened"},
                    "ENG110": {"name": "Technical Writing", "credits": 3, "prereqs": [], "category": "gened"},
                    "MATH115": {"name": "Calculus for Computing", "credits": 4, "prereqs": [], "category": "math"},
                    "CS105": {"name": "Programming Fundamentals", "credits": 4, "prereqs": [], "category": "core"},
                    "CS115": {"name": "Object-Oriented Programming", "credits": 4, "prereqs": ["CS105"], "category": "core"},
                    "CS205": {"name": "Data Structures", "credits": 4, "prereqs": ["CS115"], "category": "core"},
                    "CS215": {"name": "Computer Systems", "credits": 3, "prereqs": ["CS205"], "category": "core"},
                    "CS225": {"name": "Discrete Structures", "credits": 3, "prereqs": ["MATH115"], "category": "core"},
                    "CS305": {"name": "Algorithms", "credits": 3, "prereqs": ["CS205", "CS225"], "category": "core"},
                    "CS315": {"name": "Database Systems", "credits": 3, "prereqs": ["CS205"], "category": "core"},
                    "CS325": {"name": "Operating Systems", "credits": 3, "prereqs": ["CS215"], "category": "core"},
                    "CS335": {"name": "Software Project", "credits": 3, "prereqs": ["CS305"], "category": "core"},
                    "STAT210": {"name": "Statistics for Engineers", "credits": 3, "prereqs": ["MATH115"], "category": "math"},
                    "HUM200": {"name": "Humanities Elective", "credits": 3, "prereqs": [], "category": "humanities"},
                    "SOC200": {"name": "Social Science Elective", "credits": 3, "prereqs": [], "category": "social"},
                    "CS410": {"name": "Cloud Platforms", "credits": 3, "prereqs": ["CS325"], "category": "elective"},
                    "CS420": {"name": "Secure Systems", "credits": 3, "prereqs": ["CS325"], "category": "elective"},
                    "CS430": {"name": "Mobile Engineering", "credits": 3, "prereqs": ["CS335"], "category": "elective"},
                    "CS440": {"name": "IoT Development", "credits": 3, "prereqs": ["CS325"], "category": "elective"},
                    "CS490": {"name": "Capstone Project", "credits": 3, "prereqs": ["CS335"], "category": "capstone"},
                },
                "degree_requirements": {
                    "required_courses": [
                        "COLL100", "ENG110", "MATH115", "CS105", "CS115", "CS205", "CS215",
                        "CS225", "CS305", "CS315", "CS325", "CS335", "STAT210", "CS490",
                    ],
                    "min_credits": 120,
                    "min_humanities_credits": 6,
                    "min_social_credits": 3,
                    "min_elective_credits": 12,
                },
                "four_year_template": [
                    ["COLL100", "CS105", "MATH115", "ENG110"],
                    ["CS115", "CS205", "HUM200", "SOC200"],
                    ["CS225", "CS215", "STAT210", "GEN100"],
                    ["CS305", "CS315", "GEN101", "GEN102"],
                    ["CS325", "CS335", "ELX100", "ELX101"],
                    ["CS410", "CS420", "ELX102", "GEN103"],
                    ["CS430", "CS440", "ELX103", "ELX104"],
                    ["CS490", "ELX105", "ELX106", "ELX107"],
                ],
                "default_electives": ["CS410", "CS420", "CS430", "CS440"],
            },
        }
    },
    "Arizona State University": {
        "majors": {
            "Computer Science": {
                "courses": {
                    "ASU101": {"name": "First-Year Experience", "credits": 1, "prereqs": [], "category": "gened"},
                    "CSE110": {"name": "Principles of Programming", "credits": 3, "prereqs": [], "category": "core"},
                    "MAT142": {"name": "College Mathematics", "credits": 3, "prereqs": [], "category": "math"},
                    "MAT210": {"name": "Brief Calculus", "credits": 3, "prereqs": ["MAT142"], "category": "math"},
                    "CSE111": {"name": "Event-Driven Programming", "credits": 3, "prereqs": ["CSE110"], "category": "core"},
                    "CSE210": {"name": "Data Structures", "credits": 3, "prereqs": ["CSE111"], "category": "core"},
                    "CSE240": {"name": "Introduction to Computer Architecture", "credits": 3, "prereqs": ["CSE110"], "category": "core"},
                    "MAT230": {"name": "Discrete Mathematical Structures", "credits": 3, "prereqs": ["MAT210"], "category": "math"},
                    "CSE250": {"name": "Algorithms and Complexity", "credits": 3, "prereqs": ["CSE210", "MAT230"], "category": "core"},
                    "CSE260": {"name": "Computer Architecture and Design", "credits": 3, "prereqs": ["CSE240"], "category": "core"},
                    "CSE310": {"name": "Operating Systems Concepts", "credits": 3, "prereqs": ["CSE260"], "category": "core"},
                    "CSE330": {"name": "Database Systems", "credits": 3, "prereqs": ["CSE210"], "category": "elective"},
                    "CSE340": {"name": "Software Project I", "credits": 3, "prereqs": ["CSE250", "CSE310"], "category": "core"},
                    "CSE360": {"name": "Software Engineering and Design", "credits": 3, "prereqs": ["CSE340"], "category": "core"},
                    "STP226": {"name": "Probability and Statistics", "credits": 3, "prereqs": ["MAT210"], "category": "math"},
                    "ENG101": {"name": "Composition", "credits": 3, "prereqs": [], "category": "humanities"},
                },
                "degree_requirements": {
                    "required_courses": ["ASU101", "CSE110", "MAT142", "MAT210", "CSE111", "CSE210", "CSE240", "MAT230", "CSE250", "CSE260", "CSE310", "CSE340", "CSE360"],
                    "min_credits": 120,
                    "min_humanities_credits": 15,
                    "min_elective_credits": 12,
                },
                "four_year_template": [
                    ["ASU101", "CSE110", "MAT142", "ENG101"],
                    ["CSE111", "MAT210", "GENED100", "GENED101"],
                    ["CSE210", "CSE240", "MAT230", "GENED102"],
                    ["CSE250", "CSE260", "GENED103", "GENED104"],
                    ["CSE310", "STP226", "ELX100", "ELX101"],
                    ["CSE330", "CSE340", "ELX102", "ELX103"],
                    ["CSE360", "GENED105", "ELX104", "ELX105"],
                    ["ELX106", "ELX107", "ELX108", "ELX109"],
                ],
                "default_electives": ["CSE330"],
            },
        }
    },
}
